feat: added autocomplete for language codes
openfoodfacts/taxonomy-editor pull request #117
Opened 2022-10-17 17:54 UTC by shubham-1806

### What
Added Autocomplete for selecting language code wherever necessary using autocomplete component of MUI.

### Screenshot
![image](https://user-images.githubusercontent.com/105509441/196247856-2b04f20d-81f6-4300-a509-ce04f750d090.png)

### Fixes bug(s)
Fixes #107

2022-10-17 19:53 UTC, aadarsh-ram commented on taxonomy-editor-frontend/src/pages/allentries/index.jsx
> +    })
@shubham-1806 I think it's not required to add a new variable and push all the keys here. You can directly use `Object.keys()` to get a list of keys. Slo, this part can be removed.

2022-10-17 19:55 UTC, aadarsh-ram commented on taxonomy-editor-frontend/src/pages/allentries/index.jsx
> +                        options={languageOptions}
As I mentioned above, you can directly give this list to options.
```suggestion
                        options={Object.keys(ISO_CODES)}

```

2022-10-17 19:56 UTC, aadarsh-ram commented on taxonomy-editor-frontend/src/pages/editentry/ListTranslations.jsx
> +
Please remove this and refactor the code as I mentioned above in all three files.

2022-10-18 14:13 UTC, shubham-1806 commented
@aadarsh-ram Please review the changes

2022-10-18 15:32 UTC, aadarsh-ram approved these changes
LGTM @shubham-1806! I'd like @nobeeakon to review this as well.

2022-10-21 19:05 UTC, nobeeakon commented on taxonomy-editor-frontend/src/constants.js
> +export const ISO_CODES ={
could we get this from the library? I think it is going to be difficult to maintain this

2022-10-21 19:09 UTC, nobeeakon commented on taxonomy-editor-frontend/src/pages/search/SearchResults.jsx
> +                                setIsValidLanguageCode(ISO6391.validate(ISO_CODES[language]))
guess this could be a derived state: 
```
const isValidLanguageCode  = ISO6391.validate(newLanguageCode)
```
instead of a `useState`

2022-10-21 19:13 UTC, nobeeakon commented on taxonomy-editor-frontend/src/pages/editentry/ListTranslations.jsx
> +                        const ifDuplicateBool = renderedTranslations.some(el => (el.languageCode === ISO_CODES[language])) ||
nit: let's rename these two: `isValidLanguage` and `isDuplicateLanguage`?

2022-10-21 19:15 UTC, nobeeakon commented on taxonomy-editor-frontend/src/pages/editentry/ListTranslations.jsx
> +                        const ifDuplicateBool = renderedTranslations.some(el => (el.languageCode === ISO_CODES[language])) ||
guess this could be a derived state: 
```
const isValidLanguageCode  = ISO6391.validate(newLanguageCode)
...
```
instead of a `useState`

2022-10-21 19:17 UTC, nobeeakon commented on taxonomy-editor-frontend/src/pages/allentries/index.jsx
> +                            setIsValidLanguageCode(ISO6391.validate(ISO_CODES[language]))
guess this could be a derived state: 
```
const isValidLanguageCode  = ISO6391.validate(newLanguageCode)
```
instead of a `useState`

2022-10-21 19:25 UTC, nobeeakon commented on taxonomy-editor-frontend/src/pages/allentries/index.jsx
> +                        options={Object.keys(ISO_CODES)}
think we don't  need to have the `ISO_CODES` const. Please check the [iso-639-1 package docs](https://www.npmjs.com/package/iso-639-1), we can obtain the names and extract the codes with it.

2022-10-21 19:27 UTC, nobeeakon commented on taxonomy-editor-frontend/src/pages/allentries/index.jsx
> +                        renderInput={(params) => <TextField error={!isValidLanguageCode} {...params} label="Languages" />}
nit: does it needs a helper text as the other one?

2022-10-21 19:28 UTC, nobeeakon requested changes
thanks for the PR , nice work, just please replace the `ISO_CODES` , think we can use the features  that the [iso-639-1 package](https://www.npmjs.com/package/iso-639-1) already gives us

2022-11-15 14:25 UTC, nobeeakon approved these changes
nice work !!

2022-11-15 15:38 UTC, merged