refactor(backend,taxonomy-editor-frontend): Handle background task on frontend
openfoodfacts/taxonomy-editor pull request #316
Opened 2023-12-20 07:45 UTC by Piv94165

… frontend

### What
- 

### Screenshot

### Fixes bug(s)
- 

### Part of 
-

2023-12-20 08:08 UTC, Piv94165 commented
Link: https://github.com/openfoodfacts/taxonomy-editor/pull/304#issue-2031007807 needs to be merged prior to this PR for correct functionality.

Remarks:
During the import of a taxonomy, the task runs in the background. However, the backend is unable to send any response due to the synchronous nature of the following functions:
```
self.create_nodes(filename, multi_label)
self.create_child_link(multi_label)
self.create_previous_link(multi_label)
self.create_fulltext_index(taxonomy_name, branch_name)
self.create_parsing_errors_node(taxonomy_name, branch_name)
```
This results in the page loading indefinitely if the user tries to access existing projects while a new project is being created, as the backend cannot respond to the frontend until parsing is complete.

It appears that the issue lies in the synchronous execution of these functions. Converting them to asynchronous operations could potentially resolve this problem.
The reason why the backend can't respond to frontend seems to be the synchronism of the functions above. They should be asynchronous I think.

2024-01-09 18:24 UTC, alexgarel approved these changes
Cool. Small improvement proposed.

2024-01-09 18:24 UTC, alexgarel commented on backend/editor/entries.py
> +                await self.set_project_status(status="FAILED")
Maybe you could set project status FAILED only if create_project did not fail ? (create project could return created project and you could test it here, remember to create the variable with `None` before the `try` though to be sure it exists.

2024-01-17 18:06 UTC, alexgarel requested changes
Thank @Piv94165 !

There are still a bit of things to improve.

2024-01-17 18:06 UTC, alexgarel commented on backend/editor/entries.py
> +                        shutil.copyfileobj(uploadfile.file, f)
I think this part should be isolated in a function to make code more readable.

The function should be a context manager so it handles the tempfile transparently

```python

    @contextlib.contextmanager
    def get_taxonomy_file(self, uploadfile=None):
        ...
        with tempfile.TemporaryDirectory(prefix="taxonomy-") as tmpdir:
           ...
           yield filepath

...

    def parse_taxonomy(self, uploadfile=None):
        with self.get_taxonomy_file(uploadfile) as filepath:
            ...
```

2024-01-17 18:06 UTC, alexgarel commented on taxonomy-editor-frontend/src/pages/go-to-project/index.tsx
> +    `${API_URL}projects`
Maybe, in another PR I think we will have to provide a way to filter by status !

2024-01-17 18:06 UTC, alexgarel commented on backend/editor/entries.py
> +                        parser_object(filepath, self.branch_name, self.taxonomy_name)
In case of success, shouldn't you update the project status to "OPEN" ?

2024-01-24 17:03 UTC, alexgarel commented
@Piv94165 should we close this PR ? If I remember well you merged those changes in another PR right ?

2024-01-24 17:15 UTC, closed without merging